// service-install.mjs — register/unregister Jarela as a per-user autostart
// service on Windows, macOS, or Linux. Invoked by `jarela install-service`
// and `jarela uninstall-service` from scripts/jarela-bin.mjs.
//
// All operations are user-scoped — no admin / sudo required:
//   - Windows : Scheduled Task "Jarela" (AtLogOn, current user) → wscript
//               + VBS shim → node jarela-bin.mjs start  (hidden window)
//   - macOS   : ~/Library/LaunchAgents/com.jarela.app.plist (RunAtLoad +
//               KeepAlive) → node jarela-bin.mjs start
//   - Linux   : ~/.config/systemd/user/jarela.service
//               + `systemctl --user enable --now jarela`
//
// State for generated wrapper files lives under the platform state dir
// (matches lib/db location):
//   - Windows : %LOCALAPPDATA%\Jarela\service\
//   - macOS   : ~/Library/Application Support/Jarela/service/
//   - Linux   : ~/.config/jarela/service/

import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync, unlinkSync, rmSync } from "node:fs";
import { homedir, platform, userInfo } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const JARELA_BIN = join(HERE, "jarela-bin.mjs");
const NODE_EXE = process.execPath;
const TASK_NAME = "Jarela";
const PLIST_LABEL = "com.jarela.app";
const SYSTEMD_UNIT = "jarela.service";

function stateDir() {
  if (platform() === "win32") {
    return join(process.env.LOCALAPPDATA || join(homedir(), "AppData", "Local"), "Jarela", "service");
  }
  if (platform() === "darwin") {
    return join(homedir(), "Library", "Application Support", "Jarela", "service");
  }
  return join(homedir(), ".config", "jarela", "service");
}

function logDir() {
  if (platform() === "win32") {
    return join(process.env.LOCALAPPDATA || join(homedir(), "AppData", "Local"), "Jarela", "logs");
  }
  if (platform() === "darwin") {
    return join(homedir(), "Library", "Logs", "Jarela");
  }
  return join(homedir(), ".local", "state", "jarela", "logs");
}

function ensureDir(p) {
  if (!existsSync(p)) mkdirSync(p, { recursive: true });
}

function ok(msg) { console.log(`  ${msg}`); }
function step(msg) { console.log(`==> ${msg}`); }

// ─── Windows ───────────────────────────────────────────────────────────────
function installWindows() {
  if (!existsSync(JARELA_BIN)) throw new Error(`jarela-bin.mjs not found at ${JARELA_BIN}`);

  const dir = stateDir();
  ensureDir(dir);
  ensureDir(logDir());

  // VBS shim — wscript.exe + intWindowStyle=0 gives zero console flash at
  // logon, unlike `powershell -WindowStyle Hidden` which can flicker.
  const vbsPath = join(dir, "launcher.vbs");
  const vbs = [
    `' Generated by 'jarela install-service'. Re-run that command to refresh.`,
    `Option Explicit`,
    `Dim sh`,
    `Set sh = CreateObject("WScript.Shell")`,
    // 0 = hidden window, True = block until the child exits so Task
    // Scheduler's MultipleInstances=IgnoreNew bookkeeping stays accurate.
    `sh.Run """${NODE_EXE.replace(/\\/g, "\\\\")}"" ""${JARELA_BIN.replace(/\\/g, "\\\\")}"" start", 0, True`,
  ].join("\r\n");
  writeFileSync(vbsPath, vbs, "utf8");
  ok(`wrote ${vbsPath}`);

  step(`Registering Scheduled Task '${TASK_NAME}'`);
  const ps = [
    `$ErrorActionPreference='Stop'`,
    `$action = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument '"${vbsPath}"'`,
    `$trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME`,
    `$principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited`,
    `$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -Hidden -ExecutionTimeLimit (New-TimeSpan -Seconds 0) -RestartInterval (New-TimeSpan -Minutes 1) -RestartCount 999 -MultipleInstances IgnoreNew`,
    `$task = New-ScheduledTask -Action $action -Trigger $trigger -Principal $principal -Settings $settings -Description 'Jarela — local LangGraph chat. Auto-installed by jarela install-service.'`,
    `if (Get-ScheduledTask -TaskName '${TASK_NAME}' -ErrorAction SilentlyContinue) { Unregister-ScheduledTask -TaskName '${TASK_NAME}' -Confirm:$false }`,
    `Register-ScheduledTask -TaskName '${TASK_NAME}' -InputObject $task | Out-Null`,
    `Start-ScheduledTask -TaskName '${TASK_NAME}'`,
  ].join("; ");
  const r = spawnSync("powershell.exe", ["-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", ps], { stdio: "inherit" });
  if (r.status !== 0) throw new Error(`schtasks registration failed (exit ${r.status})`);

  ok(`task '${TASK_NAME}' started`);
  ok(`URL:   http://127.0.0.1:4312`);
  ok(`Stop:  Stop-ScheduledTask -TaskName ${TASK_NAME}`);
  ok(`Logs: ${logDir()}\\app.log  (when the launcher writes them)`);
}

function uninstallWindows() {
  step(`Unregistering Scheduled Task '${TASK_NAME}'`);
  const ps = `if (Get-ScheduledTask -TaskName '${TASK_NAME}' -ErrorAction SilentlyContinue) { Stop-ScheduledTask -TaskName '${TASK_NAME}' -ErrorAction SilentlyContinue; Unregister-ScheduledTask -TaskName '${TASK_NAME}' -Confirm:$false }`;
  const r = spawnSync("powershell.exe", ["-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", ps], { stdio: "inherit" });
  if (r.status !== 0) throw new Error(`schtasks unregistration failed (exit ${r.status})`);

  const dir = stateDir();
  if (existsSync(dir)) {
    rmSync(dir, { recursive: true, force: true });
    ok(`removed ${dir}`);
  }
  ok(`done. Data dir at %LOCALAPPDATA%\\Jarela was kept.`);
}

// ─── macOS ────────────────────────────────────────────────────────────────
function installMacOS() {
  const plistDir = join(homedir(), "Library", "LaunchAgents");
  ensureDir(plistDir);
  ensureDir(logDir());
  const plistPath = join(plistDir, `${PLIST_LABEL}.plist`);

  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${PLIST_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${NODE_EXE}</string>
    <string>${JARELA_BIN}</string>
    <string>start</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>${join(logDir(), "app.log")}</string>
  <key>StandardErrorPath</key><string>${join(logDir(), "app.log")}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key><string>/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin</string>
  </dict>
</dict>
</plist>
`;
  writeFileSync(plistPath, plist, "utf8");
  ok(`wrote ${plistPath}`);

  const uid = userInfo().uid;
  step(`Loading LaunchAgent ${PLIST_LABEL}`);
  // Unload first in case a previous version is loaded; ignore errors.
  spawnSync("launchctl", ["bootout", `gui/${uid}/${PLIST_LABEL}`], { stdio: "ignore" });
  const r = spawnSync("launchctl", ["bootstrap", `gui/${uid}`, plistPath], { stdio: "inherit" });
  if (r.status !== 0) throw new Error(`launchctl bootstrap failed (exit ${r.status})`);

  ok(`URL:   http://127.0.0.1:4312`);
  ok(`Stop:  launchctl bootout gui/${uid}/${PLIST_LABEL}`);
  ok(`Logs: ${join(logDir(), "app.log")}`);
}

function uninstallMacOS() {
  const plistPath = join(homedir(), "Library", "LaunchAgents", `${PLIST_LABEL}.plist`);
  const uid = userInfo().uid;
  step(`Unloading LaunchAgent ${PLIST_LABEL}`);
  spawnSync("launchctl", ["bootout", `gui/${uid}/${PLIST_LABEL}`], { stdio: "ignore" });
  if (existsSync(plistPath)) {
    unlinkSync(plistPath);
    ok(`removed ${plistPath}`);
  }
  ok(`done. Data dir at ~/.jarela was kept.`);
}

// ─── Linux ────────────────────────────────────────────────────────────────
function installLinux() {
  const unitDir = join(homedir(), ".config", "systemd", "user");
  ensureDir(unitDir);
  ensureDir(logDir());
  const unitPath = join(unitDir, SYSTEMD_UNIT);

  const unit = `# Generated by 'jarela install-service'. Re-run that command to refresh.
[Unit]
Description=Jarela — local LangGraph chat UI
After=network.target

[Service]
Type=simple
ExecStart=${NODE_EXE} ${JARELA_BIN} start
Restart=on-failure
RestartSec=5
StandardOutput=append:${join(logDir(), "app.log")}
StandardError=append:${join(logDir(), "app.log")}
Environment=NODE_ENV=production

[Install]
WantedBy=default.target
`;
  writeFileSync(unitPath, unit, "utf8");
  ok(`wrote ${unitPath}`);

  step(`Enabling systemd --user unit ${SYSTEMD_UNIT}`);
  const reload = spawnSync("systemctl", ["--user", "daemon-reload"], { stdio: "inherit" });
  if (reload.status !== 0) throw new Error(`systemctl --user daemon-reload failed`);
  const enable = spawnSync("systemctl", ["--user", "enable", "--now", SYSTEMD_UNIT], { stdio: "inherit" });
  if (enable.status !== 0) throw new Error(`systemctl --user enable --now ${SYSTEMD_UNIT} failed`);

  ok(`URL:   http://127.0.0.1:4312`);
  ok(`Stop:  systemctl --user stop ${SYSTEMD_UNIT}`);
  ok(`Logs: ${join(logDir(), "app.log")}  (also: journalctl --user -u ${SYSTEMD_UNIT})`);
  ok(`Note: run 'loginctl enable-linger ${userInfo().username}' if you want the service to`);
  ok(`      keep running after you log out.`);
}

function uninstallLinux() {
  step(`Disabling systemd --user unit ${SYSTEMD_UNIT}`);
  spawnSync("systemctl", ["--user", "disable", "--now", SYSTEMD_UNIT], { stdio: "ignore" });
  const unitPath = join(homedir(), ".config", "systemd", "user", SYSTEMD_UNIT);
  if (existsSync(unitPath)) {
    unlinkSync(unitPath);
    ok(`removed ${unitPath}`);
  }
  spawnSync("systemctl", ["--user", "daemon-reload"], { stdio: "ignore" });
  ok(`done. Data dir at ~/.jarela was kept.`);
}

// ─── Dispatch ─────────────────────────────────────────────────────────────
export function install() {
  const p = platform();
  console.log(`Installing Jarela as an autostart service for ${userInfo().username} (${p}).`);
  if (p === "win32")  return installWindows();
  if (p === "darwin") return installMacOS();
  if (p === "linux")  return installLinux();
  throw new Error(`unsupported platform: ${p}`);
}

export function uninstall() {
  const p = platform();
  console.log(`Removing Jarela autostart service for ${userInfo().username} (${p}).`);
  if (p === "win32")  return uninstallWindows();
  if (p === "darwin") return uninstallMacOS();
  if (p === "linux")  return uninstallLinux();
  throw new Error(`unsupported platform: ${p}`);
}
