// service-install.mjs — register/unregister Jarela as a per-user autostart
// service on Windows, macOS, or Linux. Invoked by `jarela install-service`
// and `jarela uninstall-service` from scripts/jarela-bin.mjs.
//
// All operations are user-scoped — no admin / sudo required:
//   - Windows : Scheduled Task "Jarela" (AtLogOn, current user) → wscript
//               + VBS shim → node jarela-bin.mjs start  (hidden window)
//   - macOS   : ~/Library/LaunchAgents/com.jarela.app.plist (RunAtLoad +
//               KeepAlive) → node jarela-bin.mjs start
//   - Linux   : ~/.config/systemd/user/jarela.service
//               + `systemctl --user enable --now jarela`
//
// State for generated wrapper files lives under the platform state dir
// (matches lib/db location):
//   - Windows : %LOCALAPPDATA%\Jarela\service\
//   - macOS   : ~/Library/Application Support/Jarela/service/
//   - Linux   : ~/.config/jarela/service/

import { spawnSync, execFileSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync, unlinkSync, rmSync, chmodSync } from "node:fs";
import { homedir, platform, userInfo } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const JARELA_BIN = join(HERE, "jarela-bin.mjs");
const NODE_EXE = process.execPath;
const TASK_NAME = "Jarela";
const PLIST_LABEL = "com.jarela.app";
const SYSTEMD_UNIT = "jarela.service";

// Env vars worth carrying from the installing shell into the service so
// corporate-network installs reach the LLM gateway. Services don't inherit
// the user's shell env, so without this the proxy dispatcher can't see
// HTTPS_PROXY and outbound fetches fail with bare "fetch failed".
// Re-run `jarela install-service` after editing your shell's proxy config.
const PROXY_ENV_KEYS = [
  "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY",
  "http_proxy", "https_proxy", "no_proxy",
  "NODE_EXTRA_CA_CERTS",
];

function captureProxyEnv() {
  const out = {};
  for (const k of PROXY_ENV_KEYS) {
    const v = process.env[k];
    if (v && v.length > 0) out[k] = v;
  }
  return out;
}

// Resolve the same default data dir the running server uses, so the
// extracted bundle ends up at ~/.jarela/system-ca.pem (matching the
// TS-side `getDataDir()` in lib/db/data-dir.ts). We don't run the legacy
// migrations here — install-service is a fresh-setup tool, the running
// server handles migrations on first boot.
function defaultJarelaDataDir() {
  const env = process.env.JARELA_DB_DIR;
  if (env && env.length > 0) {
    return env.startsWith("~") ? env.replace(/^~/, homedir()) : env;
  }
  if (platform() === "win32") {
    const local = process.env.LOCALAPPDATA || join(homedir(), "AppData", "Local");
    return join(local, "Jarela");
  }
  return join(homedir(), ".jarela");
}

// macOS only: extract the System + login keychain trust stores into a
// single PEM bundle under <dataDir>/system-ca.pem and inject the path
// into process.env.NODE_EXTRA_CA_CERTS so captureProxyEnv() picks it
// up and bakes it into the LaunchAgent plist (ADR-0020).
//
// Mirrors the runtime logic in lib/proxy/keychain.ts. We duplicate it
// here rather than import the TS module because this script runs as a
// CLI without a TypeScript loader, and the logic is small and stable.
function ensureSystemTrustOnDarwin() {
  if (platform() !== "darwin") return;
  if (process.env.NODE_EXTRA_CA_CERTS && process.env.NODE_EXTRA_CA_CERTS.length > 0) {
    ok(`NODE_EXTRA_CA_CERTS already set in shell env — leaving as-is`);
    return;
  }
  const keychains = [
    "/Library/Keychains/System.keychain",
    "/System/Library/Keychains/SystemRootCertificates.keychain",
    join(homedir(), "Library/Keychains/login.keychain-db"),
  ];
  const seen = new Set();
  const blocks = [];
  const used = [];
  const re = /-----BEGIN CERTIFICATE-----[\s\S]+?-----END CERTIFICATE-----/g;
  for (const kc of keychains) {
    if (!existsSync(kc)) continue;
    let stdout;
    try {
      stdout = execFileSync("/usr/bin/security", ["find-certificate", "-a", "-p", kc], {
        encoding: "utf8",
        maxBuffer: 16 * 1024 * 1024,
      });
    } catch {
      continue;
    }
    const matches = stdout.match(re) ?? [];
    let added = 0;
    for (const raw of matches) {
      const norm = raw.replace(/\r\n/g, "\n").trim();
      if (seen.has(norm)) continue;
      seen.add(norm);
      blocks.push(norm);
      added++;
    }
    if (added > 0) used.push(kc);
  }
  if (blocks.length === 0) {
    ok("system trust: no certificates extracted from keychains — skipping");
    return;
  }
  const dataDir = defaultJarelaDataDir();
  ensureDir(dataDir);
  const pemPath = join(dataDir, "system-ca.pem");
  const body =
    `# Jarela system trust bundle — generated by 'jarela install-service'.\n` +
    `# Source keychains: ${used.join(", ")}\n` +
    `# ${blocks.length} unique certificates. Re-run install-service or use the\n` +
    `# Proxy panel "Refresh trust store" button to regenerate after MDM updates.\n\n` +
    blocks.join("\n") +
    "\n";
  writeFileSync(pemPath, body, "utf8");
  try { chmodSync(pemPath, 0o600); } catch { /* best-effort */ }
  process.env.NODE_EXTRA_CA_CERTS = pemPath;
  ok(`system trust: ${blocks.length} certs from ${used.length} keychain(s) → ${pemPath}`);
}

function reportCapturedEnv(env) {
  const keys = Object.keys(env);
  if (keys.length === 0) {
    ok("no proxy/CA env vars detected — service will run with direct egress");
    return;
  }
  ok(`captured env: ${keys.join(", ")}`);
}

function xmlEscape(s) {
  return String(s)
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&apos;");
}

function stateDir() {
  if (platform() === "win32") {
    return join(process.env.LOCALAPPDATA || join(homedir(), "AppData", "Local"), "Jarela", "service");
  }
  if (platform() === "darwin") {
    return join(homedir(), "Library", "Application Support", "Jarela", "service");
  }
  return join(homedir(), ".config", "jarela", "service");
}

function logDir() {
  if (platform() === "win32") {
    return join(process.env.LOCALAPPDATA || join(homedir(), "AppData", "Local"), "Jarela", "logs");
  }
  if (platform() === "darwin") {
    return join(homedir(), "Library", "Logs", "Jarela");
  }
  return join(homedir(), ".local", "state", "jarela", "logs");
}

function ensureDir(p) {
  if (!existsSync(p)) mkdirSync(p, { recursive: true });
}

function ok(msg) { console.log(`  ${msg}`); }
function step(msg) { console.log(`==> ${msg}`); }

// macOS / Linux: SIGTERM anything currently listening on `port`. Used
// before launchd / systemd bootstrap so the new managed process can
// bind cleanly. We only call this on platforms where `lsof -t` is
// available (darwin, linux); Windows uses a different mechanism via
// Stop-ScheduledTask + the wscript shim.
function freeJarelaPort(port) {
  if (platform() === "win32") return;
  const r = spawnSync("lsof", ["-nP", `-iTCP:${port}`, "-sTCP:LISTEN", "-t"], {
    encoding: "utf8",
  });
  if (r.status !== 0 || !r.stdout) return;
  const pids = r.stdout
    .split("\n")
    .map((s) => s.trim())
    .filter((s) => /^\d+$/.test(s));
  for (const pid of pids) {
    ok(`stopping process ${pid} holding port ${port}`);
    try { process.kill(Number(pid), "SIGTERM"); } catch { /* gone already */ }
  }
  if (pids.length > 0) {
    // Brief settle so launchd doesn't see the socket in TIME_WAIT.
    spawnSync("sleep", ["1"]);
  }
}

// ─── Windows ───────────────────────────────────────────────────────────────
function installWindows() {
  if (!existsSync(JARELA_BIN)) throw new Error(`jarela-bin.mjs not found at ${JARELA_BIN}`);

  const dir = stateDir();
  ensureDir(dir);
  ensureDir(logDir());

  const proxyEnv = captureProxyEnv();
  // Set vars on the wscript PROCESS env so the spawned node inherits them.
  // VBS string literals double-up `"` to escape; we refuse `"` in values.
  const envLines = Object.entries(proxyEnv).map(([k, v]) => {
    if (v.includes("\"")) throw new Error(`refusing to write env var ${k}: contains '"'`);
    return `env("${k}") = "${v}"`;
  });

  // VBS shim — wscript.exe + intWindowStyle=0 gives zero console flash at
  // logon, unlike `powershell -WindowStyle Hidden` which can flicker.
  const vbsPath = join(dir, "launcher.vbs");
  const vbs = [
    `' Generated by 'jarela install-service'. Re-run that command to refresh.`,
    `Option Explicit`,
    `Dim sh, env`,
    `Set sh = CreateObject("WScript.Shell")`,
    `Set env = sh.Environment("PROCESS")`,
    ...envLines,
    // 0 = hidden window, True = block until the child exits so Task
    // Scheduler's MultipleInstances=IgnoreNew bookkeeping stays accurate.
    `sh.Run """${NODE_EXE.replace(/\\/g, "\\\\")}"" ""${JARELA_BIN.replace(/\\/g, "\\\\")}"" start", 0, True`,
  ].join("\r\n");
  writeFileSync(vbsPath, vbs, "utf8");
  ok(`wrote ${vbsPath}`);
  reportCapturedEnv(proxyEnv);

  step(`Registering Scheduled Task '${TASK_NAME}'`);
  const ps = [
    `$ErrorActionPreference='Stop'`,
    `$action = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument '"${vbsPath}"'`,
    `$trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME`,
    `$principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited`,
    `$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -Hidden -ExecutionTimeLimit (New-TimeSpan -Seconds 0) -RestartInterval (New-TimeSpan -Minutes 1) -RestartCount 999 -MultipleInstances IgnoreNew`,
    `$task = New-ScheduledTask -Action $action -Trigger $trigger -Principal $principal -Settings $settings -Description 'Jarela — local LangGraph chat. Auto-installed by jarela install-service.'`,
    `if (Get-ScheduledTask -TaskName '${TASK_NAME}' -ErrorAction SilentlyContinue) { Unregister-ScheduledTask -TaskName '${TASK_NAME}' -Confirm:$false }`,
    `Register-ScheduledTask -TaskName '${TASK_NAME}' -InputObject $task | Out-Null`,
    `Start-ScheduledTask -TaskName '${TASK_NAME}'`,
  ].join("; ");
  const r = spawnSync("powershell.exe", ["-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", ps], { stdio: "inherit" });
  if (r.status !== 0) throw new Error(`schtasks registration failed (exit ${r.status})`);

  ok(`task '${TASK_NAME}' started`);
  ok(`URL:   http://127.0.0.1:4312`);
  ok(`Stop:  Stop-ScheduledTask -TaskName ${TASK_NAME}`);
  ok(`Logs: ${logDir()}\\app.log  (when the launcher writes them)`);
}

function uninstallWindows() {
  step(`Unregistering Scheduled Task '${TASK_NAME}'`);
  const ps = `if (Get-ScheduledTask -TaskName '${TASK_NAME}' -ErrorAction SilentlyContinue) { Stop-ScheduledTask -TaskName '${TASK_NAME}' -ErrorAction SilentlyContinue; Unregister-ScheduledTask -TaskName '${TASK_NAME}' -Confirm:$false }`;
  const r = spawnSync("powershell.exe", ["-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", ps], { stdio: "inherit" });
  if (r.status !== 0) throw new Error(`schtasks unregistration failed (exit ${r.status})`);

  const dir = stateDir();
  if (existsSync(dir)) {
    rmSync(dir, { recursive: true, force: true });
    ok(`removed ${dir}`);
  }
  ok(`done. Data dir at %LOCALAPPDATA%\\Jarela was kept.`);
}

// ─── macOS ────────────────────────────────────────────────────────────────
function installMacOS() {
  const plistDir = join(homedir(), "Library", "LaunchAgents");
  ensureDir(plistDir);
  ensureDir(logDir());
  const plistPath = join(plistDir, `${PLIST_LABEL}.plist`);

  // ADR-0020: pull the macOS keychain trust store into NODE_EXTRA_CA_CERTS
  // before capturing the env, so the LaunchAgent plist carries it forward
  // to every restart without manual paste.
  ensureSystemTrustOnDarwin();
  const proxyEnv = captureProxyEnv();
  const proxyEntries = Object.entries(proxyEnv)
    .map(([k, v]) => `    <key>${xmlEscape(k)}</key><string>${xmlEscape(v)}</string>`)
    .join("\n");

  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${PLIST_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${NODE_EXE}</string>
    <string>${JARELA_BIN}</string>
    <string>start</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>${join(logDir(), "app.log")}</string>
  <key>StandardErrorPath</key><string>${join(logDir(), "app.log")}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key><string>/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin</string>
${proxyEntries}
  </dict>
</dict>
</plist>
`;
  writeFileSync(plistPath, plist, "utf8");
  ok(`wrote ${plistPath}`);
  reportCapturedEnv(proxyEnv);

  const uid = userInfo().uid;
  step(`Loading LaunchAgent ${PLIST_LABEL}`);
  // Unload first in case a previous version is loaded; ignore errors.
  spawnSync("launchctl", ["bootout", `gui/${uid}/${PLIST_LABEL}`], { stdio: "ignore" });
  // Free port 4312 if anything else is holding it. With RunAtLoad +
  // KeepAlive, launchd spawns the child immediately and EADDRINUSE
  // surfaces as the cryptic "Bootstrap failed: 5: Input/output error".
  freeJarelaPort(4312);
  // Clear any "disabled" mark from a previous failed bootstrap.
  spawnSync("launchctl", ["enable", `gui/${uid}/${PLIST_LABEL}`], { stdio: "ignore" });
  const r = spawnSync("launchctl", ["bootstrap", `gui/${uid}`, plistPath], { stdio: "inherit" });
  if (r.status !== 0) {
    console.error(`launchctl bootstrap failed (exit ${r.status}). Common causes:`);
    console.error(`  - port 4312 in use (check: lsof -nP -iTCP:4312 -sTCP:LISTEN)`);
    console.error(`  - agent loaded elsewhere (try: launchctl bootout gui/${uid}/${PLIST_LABEL})`);
    console.error(`  - agent disabled (try: launchctl enable gui/${uid}/${PLIST_LABEL})`);
    throw new Error(`launchctl bootstrap failed (exit ${r.status})`);
  }

  ok(`URL:   http://127.0.0.1:4312`);
  ok(`Stop:  launchctl bootout gui/${uid}/${PLIST_LABEL}`);
  ok(`Logs: ${join(logDir(), "app.log")}`);
}

function uninstallMacOS() {
  const plistPath = join(homedir(), "Library", "LaunchAgents", `${PLIST_LABEL}.plist`);
  const uid = userInfo().uid;
  step(`Unloading LaunchAgent ${PLIST_LABEL}`);
  spawnSync("launchctl", ["bootout", `gui/${uid}/${PLIST_LABEL}`], { stdio: "ignore" });
  if (existsSync(plistPath)) {
    unlinkSync(plistPath);
    ok(`removed ${plistPath}`);
  }
  ok(`done. Data dir at ~/.jarela was kept.`);
}

// ─── Linux ────────────────────────────────────────────────────────────────
function installLinux() {
  const unitDir = join(homedir(), ".config", "systemd", "user");
  ensureDir(unitDir);
  ensureDir(logDir());
  const unitPath = join(unitDir, SYSTEMD_UNIT);

  const proxyEnv = captureProxyEnv();
  // systemd's `Environment="KEY=VALUE"` form quotes the whole pair so values
  // containing `=`, spaces, or `;` survive the parser. Embedded `"` get
  // escaped per systemd.exec(5) rules — we just refuse them, since proxy
  // URLs and CA paths don't contain raw quotes in practice.
  const proxyLines = Object.entries(proxyEnv)
    .map(([k, v]) => {
      if (/["\\\n]/.test(v)) {
        throw new Error(`refusing to write env var ${k}: contains quote/backslash/newline`);
      }
      return `Environment="${k}=${v}"`;
    })
    .join("\n");

  const unit = `# Generated by 'jarela install-service'. Re-run that command to refresh.
[Unit]
Description=Jarela — local LangGraph chat UI
After=network.target

[Service]
Type=simple
ExecStart=${NODE_EXE} ${JARELA_BIN} start
Restart=on-failure
RestartSec=5
StandardOutput=append:${join(logDir(), "app.log")}
StandardError=append:${join(logDir(), "app.log")}
Environment=NODE_ENV=production
${proxyLines}

[Install]
WantedBy=default.target
`;
  writeFileSync(unitPath, unit, "utf8");
  ok(`wrote ${unitPath}`);
  reportCapturedEnv(proxyEnv);

  // Free port 4312 first so the unit's first start doesn't collide with
  // a stray dev server / unmanaged install.
  freeJarelaPort(4312);

  step(`Enabling systemd --user unit ${SYSTEMD_UNIT}`);
  const reload = spawnSync("systemctl", ["--user", "daemon-reload"], { stdio: "inherit" });
  if (reload.status !== 0) throw new Error(`systemctl --user daemon-reload failed`);
  const enable = spawnSync("systemctl", ["--user", "enable", "--now", SYSTEMD_UNIT], { stdio: "inherit" });
  if (enable.status !== 0) throw new Error(`systemctl --user enable --now ${SYSTEMD_UNIT} failed`);

  ok(`URL:   http://127.0.0.1:4312`);
  ok(`Stop:  systemctl --user stop ${SYSTEMD_UNIT}`);
  ok(`Logs: ${join(logDir(), "app.log")}  (also: journalctl --user -u ${SYSTEMD_UNIT})`);
  ok(`Note: run 'loginctl enable-linger ${userInfo().username}' if you want the service to`);
  ok(`      keep running after you log out.`);
}

function uninstallLinux() {
  step(`Disabling systemd --user unit ${SYSTEMD_UNIT}`);
  spawnSync("systemctl", ["--user", "disable", "--now", SYSTEMD_UNIT], { stdio: "ignore" });
  const unitPath = join(homedir(), ".config", "systemd", "user", SYSTEMD_UNIT);
  if (existsSync(unitPath)) {
    unlinkSync(unitPath);
    ok(`removed ${unitPath}`);
  }
  spawnSync("systemctl", ["--user", "daemon-reload"], { stdio: "ignore" });
  ok(`done. Data dir at ~/.jarela was kept.`);
}

// ─── Dispatch ─────────────────────────────────────────────────────────────
export function install() {
  const p = platform();
  console.log(`Installing Jarela as an autostart service for ${userInfo().username} (${p}).`);
  if (p === "win32")  return installWindows();
  if (p === "darwin") return installMacOS();
  if (p === "linux")  return installLinux();
  throw new Error(`unsupported platform: ${p}`);
}

export function uninstall() {
  const p = platform();
  console.log(`Removing Jarela autostart service for ${userInfo().username} (${p}).`);
  if (p === "win32")  return uninstallWindows();
  if (p === "darwin") return uninstallMacOS();
  if (p === "linux")  return uninstallLinux();
  throw new Error(`unsupported platform: ${p}`);
}
